### ISSUE TITLE
Implement `up` command

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#1]

**Comment by jkurz** [comment]
Here are some thoughts around requirements for this feature.

### SHIPMENT
- we need to check if the shipment has been created
- if not then create it with the appropriate fields. `group`

### ENVIRONMENT
- check to see if environment exists
- if not create it and add all values accordingly
- it it does, then get the difference of each value. ENVIRONMENT, PORTS, PROVIDERS
- each of these values will have specific directives according to the types of changes that were made. (eg if anything changes with a PORT value, we need to bring the shipment down and back up again)

### PORTS
- add ability to name PORT values via harbor compose
- add options for PUBLIC_PORT, PRIVATE_KEY, PUBLIC_KEY, CERT_CHAIN, PRIMARY, PUBLIC, EXTERNAL (there are even more values that are part of the shipit PORT model) This is by far the most advanced portion of shipit and will need the most attentiion to make sure it's done right)
- We need to be able to add a HEALTHCHECK value to any one of the PORTS and only one PORT can have a HEALTHCHECK value attached
- Maybe we can sit down and think of a way to make this simpler. It's already pretty complex and I don't want to make it hard.

A suggestion would be to create a new model in harbor-compose called harbor_ports: 

```
harbor_ports:
 - PORT:
     PUBLIC_PORT: 80
     VALUE: 8080
     HEALTHCHECK: /hc
 - SSL_PORT
    PUBLIC_PORT: 443
    VALUE: 443
```

### PROVIDERS
- force the user to enter a barge value on their shipment level. No default barges if using harbor-compose. (we could add a cmd, `harbor-compose list-barges` to list the current barges)
- Always use ec2 for now as the PROVIDER name, this will make it simple so users don't need to decide which PROVIDER they need to be in. 

All of this logic should be seamless. The user should not know or care about any of its implementation.
