### ISSUE TITLE
add 'restart' command

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#109]
A lot of developers are asking how to "restart" their application.  Adding a `restart` command could update a dummy environment variable causing k8s to do a new rolling deployment.

```
$ harbor-compose restart
```

**Comment by jritsema** [comment]
Couple things I noticed while testing this...

1)  We're adding a new envvar each time restart is run. e.g., 
```
restart_20170821085717: test
restart_20170821085751: test
```
I think we should just update the same envvar each time and call it something like:
```
HARBOR_RESTART: jritsema-20170821085717
```

2)  I think we should update the short help to be consistent with the other commands (application instead of Shipment).
```
  down        Stop your application
  restart     Restart a Shipment
  up          Start your application
```

**Comment by jkurz** [comment]
https://github.com/turnerlabs/harbor-compose/pull/119
