### ISSUE TITLE
Harbor-compose throws panic error....

### ISSUE THREAD

**Issue by gaddamanugu** [turnerlabs/harbor-compose#40]
On repeated harbor-compose logs calls (as the follows is still backlog)... getting the following..

Logs For:  datacity-flow dev
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x479d00, 0xc82000e060)
  /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/turnerlabs/harbor-compose/cmd.printMergedLogs(0x0, 0xc8201fc000, 0x2, 0x4)
  /usr/local/go_workspace/src/github.com/turnerlabs/harbor-compose/cmd/logs.go:92 +0xd13
github.com/turnerlabs/harbor-compose/cmd.logs(0x76eb40, 0x78ec00, 0x0, 0x0)
  /usr/local/go_workspace/src/github.com/turnerlabs/harbor-compose/cmd/logs.go:50 +0x487
github.com/turnerlabs/harbor-compose/vendor/github.com/spf13/cobra.(_Command).execute(0x76eb40, 0x78ec00, 0x0, 0x0, 0x0, 0x0)
  /usr/local/go_workspace/src/github.com/turnerlabs/harbor-compose/vendor/github.com/spf13/cobra/command.go:588 +0x896
github.com/turnerlabs/harbor-compose/vendor/github.com/spf13/cobra.(_Command).ExecuteC(0x76ed60, 0x76eb40, 0x0, 0x0)
  /usr/local/go_workspace/src/github.com/turnerlabs/harbor-compose/vendor/github.com/spf13/cobra/command.go:674 +0x55c
github.com/turnerlabs/harbor-compose/vendor/github.com/spf13/cobra.(*Command).Execute(0x76ed60, 0x0, 0x0)
  /usr/local/go_workspace/src/github.com/turnerlabs/harbor-compose/vendor/github.com/spf13/cobra/command.go:633 +0x2d
github.com/turnerlabs/harbor-compose/cmd.Execute(0x5db2fc, 0x6, 0x5dd6c0, 0x13)
  /usr/local/go_workspace/src/github.com/turnerlabs/harbor-compose/cmd/root.go:41 +0x7d
main.main()
  /usr/local/go_workspace/src/github.com/turnerlabs/harbor-compose/main.go:9 +0x47

**Comment by jkurz** [comment]
This is caused because we upgraded docker on our hosts. When we did this, it caused the logs to start having leading bytes as headers in them. This was causing a panic, as harbor-compose could not read the logs' timestamp correctly. There is a fix in place to remove these first 8 bytes.

https://github.com/turnerlabs/helmit-api/pull/20
