### ISSUE TITLE
Harbor compose authorization fails for passwords over 20 characters

### ISSUE THREAD

**Issue by nabil-money** [turnerlabs/harbor-compose#60]
It appears that the maximum allowed password is 20 characters. But my password exceeds that and is valid on Harbor, Turner email, Argonaut, etc. 

Should this check allow passwords over 20 characters? 

https://github.com/turnerlabs/harbor-compose/blob/27eeb5e8fc811caa4a79e162809b6e64a4e53574/vendor/github.com/turnerlabs/harbor-auth-client/authclient.go#L47

Thanks

**Comment by jritsema** [comment]
This should be fixed.  @nabil-money thanks for submitting and let us know if you have any more issues.

https://github.com/turnerlabs/harbor-compose/releases/tag/v0.8.2

**Comment by nabil-money** [comment]
Thanks 👍
