### ISSUE TITLE
Add environment variable substitution

### ISSUE THREAD

**Issue by mchastain-turner** [turnerlabs/harbor-compose#88]
harbor-compose should allow for environment variable substitution like docker-compose does: 
https://docs.docker.com/compose/environment-variables/

**Comment by jritsema** [comment]
Hey @mchastain-turner, variable substitution already works for environment variables only.  [This issue](https://github.com/turnerlabs/harbor-compose/issues/82) would bring support for other compose constructs like images and ports.
